# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 18:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Fragmento de texto extraido del texto de la seccion')),
                ('pagina', models.PositiveIntegerField(blank=True, help_text='Nº pagina donde comienza esta publicacion en la seccion', null=True)),
                ('metadatos', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='contiene informacion estructurada', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeccionBO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[(1, '1º Sección: Legislación – Normativas'), (2, '2º Sección: Judiciales'), (3, '3º Sección: Sociedades – Personas Jurídicas – Asambleas y Otras'), (4, '4º Sección: Concesiones, Licitaciones, Servicios Publ. y Contrataciones'), (5, '5º Sección: Municipalidades y Comunas: Legislación – Normativas')], max_length=20)),
                ('fecha', models.DateField()),
                ('texto', models.TextField(help_text='texto crudo, conversion del pdf')),
                ('url', models.URLField(help_text='url original del pdf')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='seccionbo',
            unique_together=set([('seccion', 'fecha')]),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='bo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pillo.SeccionBO'),
        ),
    ]
